# Generated by Django 5.2.6 on 2026-04-15 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('exception_type', models.CharField(db_index=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('sample_traceback', models.TextField(blank=True)),
                ('sample_request_path', models.CharField(blank=True, max_length=500)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=200)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Last time an alert email was sent for this group.', null=True)),
            ],
            options={
                'ordering': ('-last_seen',),
                'indexes': [models.Index(fields=['resolved', '-last_seen'], name='ai_monitori_resolve_eb2be5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_query', models.TextField(blank=True)),
                ('request_body_preview', models.TextField(blank=True)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('traceback', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='ai_monitoring.errorlog')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['group', '-timestamp'], name='ai_monitori_group_i_cab612_idx')],
            },
        ),
    ]
